### ISSUE TITLE
Please explain: How to run in Oqtane?

### ISSUE THREAD

**Issue by Line4GitHub** [2sic/app-tutorial-razor#1]
In Oqtane 3.1

Click: Install App, Open: Import App Dialog Box, Select: 2sxcApp_Tutorial-Razor_12.5.0.zip, Click: Import.

Then...

The import failed. See the messages below for more information.

Could not import the app / package: File name, Directory name,, Error.
'E:\inetpub\Oqtane2SXC\wwwroot\Modules\ToSic.Sxc\_\YEWDPma2\Apps\Tutorial-Razor\2sexy\basics\assets\urls\g?gle plus.png' Would you like to install it using another folder name? 

Using another folder, The same error occurs!
And,
Import: 2sxcApp_MobiusForms_5.0.1.zip, The same error occurs!

Thank you very much!

**Comment by iJungleboy** [comment]
Hi @Line4GitHub 

ATM 2sxc doesn't yet run on Oqtane 3 - which was just released a few days ago. We must first ensure compatibility. This will take about a week to complete. 

I'm closing this task, as it's an general 2sxc issue and not specific to this app.

**Comment by Line4GitHub** [comment]
Thank You very much for your reply!
