### ISSUE TITLE
Customize Toolbars shows rendering error

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-tutorial-razor#3]
In Customize Edit UI/UX, 2. Customize Toolbars - when you go to the page you currently get an 'Error rendering template.'
[https://2sxc.org/dnn-tutorials/en/razor/ui100/page](https://2sxc.org/dnn-tutorials/en/razor/ui100/page)

**Comment by iJungleboy** [comment]
thanks! we fixed it. 

Was something related to the modified configuration - features are now managed better, but require you to configure them again after an upgrade.

We'll have to see how we can make people aware of this...
