### ISSUE TITLE
The extension '.csv' is not allowed. The file has not been added.

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-tutorial-razor#5]
When installing on DNN 9.10.2 with a recently upgraded 2sxc 14.07.04, during the install (app import) you get the following warning because DNN does not allow CSV files by default.

Message: The extension '.csv' is not allowed. The file has not been added.

**Comment by getBlup** [comment]
Thank you for reporting the issue. It is resolved in the [14.07.05 Release](https://github.com/2sic/app-tutorial-razor/releases/tag/v14.07.05).
