### ISSUE TITLE
Demo does not work for Anonymous users, cannot add Entity (as draft)

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-tutorial-razor#6]
Installed the latest version of the tutorial, v14.7.3 on DNN 9.10.2 with a recently upgraded 2sxc 14.7.4. 

Go to the Custom Micro-WYSIWYG Input Field example (under Customize Edit UI/UX, lightweight, 4 button), Press the add button to see/test...  enter something and save.
 
You get a 403 error on the JS console.
 
It was not obvious to us, but the fix is to get the site registered as Patron, then go to Manage Apps, Features tab, then expand Core+ (free for everyone who registers) and Enable 'Public Use of Edit Form` which is disabled by default.
 
So, just a recommendation that you put a note/alert on the page (and all pages where necessary) for people who install this app so they learn/know how to get it working.

![image](https://user-images.githubusercontent.com/653301/178018746-7fcb6efb-4975-43a3-a55e-da5b95dc150c.png)

**Comment by getBlup** [comment]
Thank you for the suggestion. We added it in the [release 14.07.05](https://github.com/2sic/app-tutorial-razor/releases/tag/v14.07.05).
